function A = matrixA(xp_dot_star, yp_dot_star, theta_star, psi_star, phi_star, K1, K2)
    
    global L L1 L2 d 
    

    
    A = zeros(5);
    
    a11 = -K1; a12 = 0; a13 = 0; a14 = 0; a15 = 0;
    
    a21 = 0; a22 = -K2; a23 = 0; a24 = 0; a25 = 0;
    
    a31 = (-K1/L)*sin(phi_star)*cos(theta_star + phi_star);
    a32 = (-K2/L)*sin(phi_star)*sin(theta_star + phi_star);
    a33 = (-sin(phi_star)/L)*(sin(theta_star + phi_star)*xp_dot_star -...
           cos(theta_star + phi_star)*yp_dot_star);
    a34 = 0;
    a35 = (1/L)*(cos(theta_star + 2*phi_star)*xp_dot_star +...
           sin(theta_star + 2*phi_star)*yp_dot_star);
       
    a41 = (K1/(L*L2))*(L1*sin(phi_star)*cos(psi_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi_star))*cos(theta_star + phi_star);
    a42 = (K2/(L*L2))*(L1*sin(phi_star)*cos(psi_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi_star))*sin(theta_star + phi_star);
    a43 = (-1/(L*L2))*(L1*sin(phi_star)*cos(psi_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi_star))*...
           (-sin(theta_star + phi_star)*xp_dot_star + cos(theta_star + phi_star)*yp_dot_star);
    a44 = (-1/(L*L2))*(-L1*sin(phi_star)*sin(psi_star) + L*cos(phi_star)*cos(psi_star))*...
           (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star);
    a45 = (-1/(L*L2))*(L1*cos(phi_star)*cos(psi_star) + L2*cos(phi_star) -...
           L*sin(phi_star)*sin(psi_star))*...
           (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star) +...
           (1/(L*L2))*(L1*sin(phi_star)*cos(psi_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi_star))*...
           (sin(theta_star + phi_star)*xp_dot_star - cos(theta_star + phi_star)*yp_dot_star);
    
    a51 = K1*((cos(theta_star + phi_star)*sin(phi_star))/L +...
           sin(theta_star + phi_star)/d);
    a52 = K2*((sin(theta_star + phi_star)*sin(phi_star))/L -...
           cos(theta_star + phi_star)/d);
    a53 = ((sin(theta_star + phi_star)*sin(phi_star))/L -...
           cos(theta_star + phi_star)/d)*xp_dot_star -...
           ((cos(theta_star + phi_star)*sin(phi_star))/L +...
           sin(theta_star + phi_star)/d)*yp_dot_star;
    a54 = 0;
    a55 = (-(1/L)*cos(theta_star + 2*phi_star) -...
          (1/d)*cos(theta_star + phi_star))*xp_dot_star -...
          ((1/L)*sin(theta_star + 2*phi_star) +...
          (1/d)*sin(theta_star + phi_star))*yp_dot_star;
      
   A = [a11 a12 a13 a14 a15;
        a21 a22 a23 a24 a25;
        a31 a32 a33 a34 a35;
        a41 a42 a43 a44 a45;
        a51 a52 a53 a54 a55];
end