function A = matrixA(xp_dot_star, yp_dot_star, theta_star, psi1_star, psi2_star, phi_star, K1, K2)

    global L L1 L2 L3 L4 d
    
    A = zeros(6);
    
    a11 = -K1; a12 = 0; a13 = 0; a14 = 0; a15 = 0; a16 = 0;
    
    a21 = 0; a22 = -K2; a23 = 0; a24 = 0; a25 = 0; a26 = 0;
    
    a31 = (-K1/L)*sin(phi_star)*cos(theta_star + phi_star);
    a32 = (-K2/L)*sin(phi_star)*sin(theta_star + phi_star);
    a33 = (-sin(phi_star)/L)*(sin(theta_star + phi_star)*xp_dot_star -...
           cos(theta_star + phi_star)*yp_dot_star);
    a34 = 0;
    a35 = 0;
    a36 = (1/L)*(cos(theta_star + 2*phi_star)*xp_dot_star +...
           sin(theta_star + 2*phi_star)*yp_dot_star);
       
    a41 = (K1/(L*L2))*(L1*sin(phi_star)*cos(psi1_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi1_star))*cos(theta_star + phi_star);
    a42 = (K2/(L*L2))*(L1*sin(phi_star)*cos(psi1_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi1_star))*sin(theta_star + phi_star);
    a43 = (-1/(L*L2))*(L1*sin(phi_star)*cos(psi1_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi1_star))*...
           (-sin(theta_star + phi_star)*xp_dot_star + cos(theta_star + phi_star)*yp_dot_star);
    a44 = (-1/(L*L2))*(-L1*sin(phi_star)*sin(psi1_star) + L*cos(phi_star)*cos(psi1_star))*...
           (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star);
    a45 = 0;
    a46 = (-1/(L*L2))*(L1*cos(phi_star)*cos(psi1_star) + L2*cos(phi_star) -...
           L*sin(phi_star)*sin(psi1_star))*...
           (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star) -...
           (1/(L*L2))*(L1*sin(phi_star)*cos(psi1_star) + L2*sin(phi_star) +...
           L*cos(phi_star)*sin(psi1_star))*...
           (-sin(theta_star + phi_star)*xp_dot_star + cos(theta_star + phi_star)*yp_dot_star);
    
    a51 = ((L1*sin(phi_star)/(L*L4))*((L2 + L3)*cos(psi1_star)*cos(psi2_star)/L2 + ...
            L4*cos(psi1_star)/L2 - cos(psi1_star + psi2_star)) + ...
                (cos(phi_star)*sin(psi1_star)/L2)*((L2 + L3)*cos(psi2_star)/L4 + 1) - ...
                    cos(phi_star)*sin(psi1_star + psi2_star)/L4)* ...
                        (- K1*cos(theta_star + phi_star));
    a52 = ((L1*sin(phi_star)/(L*L4))*((L2 + L3)*cos(psi1_star)*cos(psi2_star)/L2 + ...
            L4*cos(psi1_star)/L2 - cos(psi1_star + psi2_star)) + ...
                (cos(phi_star)*sin(psi1_star)/L2)*((L2 + L3)*cos(psi2_star)/L4 + 1) - ...
                    cos(phi_star)*sin(psi1_star + psi2_star)/L4)* ...
                        (- K2*sin(theta_star + phi_star));
    a53 = ((L1*sin(phi_star)/(L*L4))*((L2 + L3)*cos(psi1_star)*cos(psi2_star)/L2 + ...
            L4*cos(psi1_star)/L2 - cos(psi1_star + psi2_star)) + ...
                (cos(phi_star)*sin(psi1_star)/L2)*((L2 + L3)*cos(psi2_star)/L4 + 1) - ...
                    cos(phi_star)*sin(psi1_star + psi2_star)/L4)* ...
                    (- sin(theta_star + phi_star)*xp_dot_star + cos(theta_star + phi_star)*yp_dot_star);
    a54 = ((L1*sin(phi_star)/(L*L4))*(-(L2 + L3)*sin(psi1_star)*cos(psi2_star)/L2 - ...
            L4*sin(psi1_star)/L2 + sin(psi1_star + psi2_star)) + ...
                (cos(phi_star)*cos(psi1_star)/L2)*((L2 + L3)*cos(psi2_star)/L4 + 1) - ...
                    cos(phi_star)*cos(psi1_star + psi2_star)/L4)* ...
                        (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star);
    a55 = ((L1*sin(phi_star)/(L*L4))*(-(L2 + L3)*cos(psi1_star)*sin(psi2_star)/L2 + ...
            sin(psi1_star + psi2_star)) - (L2 + L3)*cos(phi_star)*sin(psi1_star)*sin(psi2_star)/(L2*L4) - ...
                    cos(phi_star)*cos(psi1_star + psi2_star)/L4)* ...
                        (cos(theta_star + phi_star)*xp_dot_star + sin(theta_star + phi_star)*yp_dot_star);
    a56 = ((L1*cos(theta_star + 2*phi_star)/(L*L4))* ...
            ((L2 + L3)*cos(psi1_star)*cos(psi2_star)/L2 + ...
                L4*cos(psi1_star)/L2 - cos(psi1_star + psi2_star)) - ...
                    (sin(psi1_star)*sin(theta_star + 2*phi_star)/L2)* ...
                        ((L2 + L3)*cos(psi2_star)/L4 + 1) + sin(psi1_star + psi2_star)*sin(theta_star + 2*phi_star)/L4)*xp_dot_star + ...
                            ((L1*sin(theta_star + 2*phi_star)/(L*L4))* ...
                                ((L2 + L3)*cos(psi1_star)*cos(psi2_star)/L2 + ...
                                    L4*cos(psi1_star)/L2 - cos(psi1_star + psi2_star)) + ...
                                        (sin(psi1_star)*cos(theta_star + 2*phi_star)/L2)* ...
                                            ((L2 + L3)*cos(psi2_star)/L4 + 1) - sin(psi1_star + psi2_star)*cos(theta_star + 2*phi_star)/L4)*yp_dot_star;
    
    a61 = K1*((cos(theta_star + phi_star)*sin(phi_star))/L +...
           sin(theta_star + phi_star)/d);
    a62 = K2*((sin(theta_star + phi_star)*sin(phi_star))/L -...
           cos(theta_star + phi_star)/d);
    a63 = ((sin(theta_star + phi_star)*sin(phi_star))/L -...
           cos(theta_star + phi_star)/d)*xp_dot_star -...
           ((cos(theta_star + phi_star)*sin(phi_star))/L +...
           sin(theta_star + phi_star)/d)*yp_dot_star;
    a64 = 0;
    a65 = 0;
    a66 = (-(1/L)*cos(theta_star + 2*phi_star) -...
          (1/d)*cos(theta_star + phi_star))*xp_dot_star -...
          ((1/L)*sin(theta_star + 2*phi_star) +...
          (1/d)*sin(theta_star + phi_star))*yp_dot_star;
      
    A = [a11 a12 a13 a14 a15 a16;
         a21 a22 a23 a24 a25 a26;
         a31 a32 a33 a34 a35 a36;
         a41 a42 a43 a44 a45 a46;
         a51 a52 a53 a54 a55 a56;
         a61 a62 a63 a64 a65 a66];
    
end